### ISSUE TITLE
Support for new YouTube channel link format

### ISSUE THREAD

**Issue by heyitspixl** [stadust/pointercrate#82]
Currently, the channel link connected to your account is only valid for the old YouTube channel link formats:

'youtube.com/channel/{channel_id}' or 'youtube.com/c/{custom_channel_id}/' or 'youtube.com/user/{username}/'

YouTube now also uses handles for channels, which is not yet supported:

'youtube.com/@{handle}'

**Comment by stadust** [comment]
Huh, interesting, thanks for reporting! This can be fixed by adjusting the parsing logic here: https://github.com/stadust/pointercrate/blob/06c5c784ffeb284f411ea0a9135ebfa0c1ddab4d/pointercrate-user/src/video.rs#L22-L37
in case anyone wants to PR (I don't really have time to work on pointercrate these days sadly :( )

**Comment by stadust** [comment]
This was fixed by #83
